<?php
/**
 * ⚠️ AUTO-GENERATED CODE — DO NOT MODIFY MANUALLY ⚠️
 *
 * This section of code was automatically generated by Tonka tool sanbox script.
 * It is part of a system designed to ensure consistency, reduce human error, and streamline updates.
 *
 * Any manual changes made here will be lost the next time the code is regenerated.
 * If modifications are necessary, please update the source templates or configuration files
 * that drive the generation process, rather than editing this file directly.
 *
 * Timestamp: 2025-08-27T00:09:52Z
 * Generator: Tonka Sandbox
 *
 * Purpose: Maintain integrity and automation across deployments.
 * Human intervention is neither required nor recommended.
 */


include_once dirname(__DIR__, 5). '/vendor/autoload.php';

return \App\Models\Admin::where('gender = ?', ['male']) ->first();