<?php
namespace Clicalmani\Foundation\Sandbox;

class Sandbox
{
    private static $tmp_name = '__.php';

    /**
     * Evaluate a PHP expression
     * 
     * @param string $expression
     * @param ?array $args
     * @param ?bool $exec
     * 
     * @return mixed
     */
    public static function eval(string $expression, ?array $args = [], ?bool $exec = false) : mixed
    {
        $args     = serialize($args);

        $content = <<<EVAL
        <?php
        \$serialized = <<<ARGS
        $args
        ARGS;
        extract(unserialize(\$serialized));
        \n\n
        EVAL;

        if (TRUE === $exec) $content .= "return $expression;";
        else $content .= <<<EVAL
        return <<<DELIMITER
            $expression
        DELIMITER;
        EVAL;
        
        return self::getResult($content);
    }

    public static function query(string $expression) : mixed
    {
        $timestamp = gmdate("Y-m-d\TH:i:s\Z");

        $content = <<<EVAL
        <?php
        /**
         * ⚠️ AUTO-GENERATED CODE — DO NOT MODIFY MANUALLY ⚠️
         *
         * This section of code was automatically generated by Tonka tool sanbox script.
         * It is part of a system designed to ensure consistency, reduce human error, and streamline updates.
         *
         * Any manual changes made here will be lost the next time the code is regenerated.
         * If modifications are necessary, please update the source templates or configuration files
         * that drive the generation process, rather than editing this file directly.
         *
         * Timestamp: $timestamp
         * Generator: Tonka Sandbox
         *
         * Purpose: Maintain integrity and automation across deployments.
         * Human intervention is neither required nor recommended.
         */


        include_once dirname(__DIR__, 5). '/vendor/autoload.php';\n\n
        EVAL;

        $content .= "return $expression;";
        
        file_put_contents(__DIR__ . '/index.php', $content, LOCK_EX);

        return include __DIR__ . '/index.php';
    }

    private static function getResult(string $content)
    {
        file_put_contents(sys_get_temp_dir() . '/' . static::$tmp_name, $content, LOCK_EX);
        return include sys_get_temp_dir() . '/' . static::$tmp_name;
    }
}
